import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Product from '#models/product'
import { DateTime } from 'luxon'
import { randomUUID } from 'node:crypto'

export default class ProductSeeder extends BaseSeeder {
  public async run() {
    await Product.createMany([
      {
        id: randomUUID(),
        name: 'Paracetamol',
        manufacturingDate: DateTime.now().minus({ months: 6 }),
        expiryDate: DateTime.now().plus({ years: 2 }),
        initialStock: 100,
        stock: 80,
        buyingPrice: 5,
        sellingPrice: 10,
        isLowStock: false,
        supplier: 'MediCorp',
        drug: 'Paracetamol',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Ibuprofen',
        manufacturingDate: DateTime.now().minus({ months: 3 }),
        expiryDate: DateTime.now().plus({ years: 1 }),
        initialStock: 150,
        stock: 50,
        buyingPrice: 7,
        sellingPrice: 14,
        isLowStock: true,
        supplier: 'PharmaWorks',
        drug: 'Ibuprofen',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Amoxicillin',
        manufacturingDate: DateTime.now().minus({ months: 4 }),
        expiryDate: DateTime.now().plus({ years: 1, months: 6 }),
        initialStock: 200,
        stock: 120,
        buyingPrice: 10,
        sellingPrice: 20,
        isLowStock: false,
        supplier: 'BioMed',
        drug: 'Amoxicillin',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Cetirizine',
        manufacturingDate: DateTime.now().minus({ months: 2 }),
        expiryDate: DateTime.now().plus({ years: 2 }),
        initialStock: 50,
        stock: 15,
        buyingPrice: 3,
        sellingPrice: 8,
        isLowStock: true,
        supplier: 'MediCorp',
        drug: 'Cetirizine',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Aspirin',
        manufacturingDate: DateTime.now().minus({ months: 5 }),
        expiryDate: DateTime.now().plus({ years: 3 }),
        initialStock: 300,
        stock: 250,
        buyingPrice: 6,
        sellingPrice: 12,
        isLowStock: false,
        supplier: 'HealthPlus',
        drug: 'Aspirin',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Metformin',
        manufacturingDate: DateTime.now().minus({ months: 8 }),
        expiryDate: DateTime.now().plus({ years: 2 }),
        initialStock: 200,
        stock: 60,
        buyingPrice: 8,
        sellingPrice: 16,
        isLowStock: true,
        supplier: 'WellnessPharm',
        drug: 'Metformin',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Atorvastatin',
        manufacturingDate: DateTime.now().minus({ months: 6 }),
        expiryDate: DateTime.now().plus({ years: 2 }),
        initialStock: 120,
        stock: 40,
        buyingPrice: 9,
        sellingPrice: 18,
        isLowStock: true,
        supplier: 'CardioCare',
        drug: 'Atorvastatin',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Omeprazole',
        manufacturingDate: DateTime.now().minus({ months: 7 }),
        expiryDate: DateTime.now().plus({ years: 1, months: 6 }),
        initialStock: 250,
        stock: 200,
        buyingPrice: 5,
        sellingPrice: 11,
        isLowStock: false,
        supplier: 'DigestivePharm',
        drug: 'Omeprazole',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Losartan',
        manufacturingDate: DateTime.now().minus({ months: 5 }),
        expiryDate: DateTime.now().plus({ years: 2, months: 3 }),
        initialStock: 180,
        stock: 130,
        buyingPrice: 7,
        sellingPrice: 15,
        isLowStock: false,
        supplier: 'HeartWell',
        drug: 'Losartan',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
      {
        id: randomUUID(),
        name: 'Levothyroxine',
        manufacturingDate: DateTime.now().minus({ months: 9 }),
        expiryDate: DateTime.now().plus({ years: 1, months: 9 }),
        initialStock: 90,
        stock: 20,
        buyingPrice: 4,
        sellingPrice: 9,
        isLowStock: true,
        supplier: 'ThyroPharm',
        drug: 'Levothyroxine',
        userId: 'c0dfe4df-c3ef-4d47-afad-49405fd3e77e',
      },
    ])
  }
}
