webservers:
  hosts:
    webserver01:
      ansible_host: "{{ lookup('env', 'HOST', default='') | default(omit) }}"
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  vars:
    ansible_user: "{{ lookup('env', 'SSH_USER', default='') | default(omit) }}"
