webservers:
  hosts:
    webserver01:
      ansible_host: "{{ lookup('env', 'ANSIBLE_HOST', default='') | default(omit) }}"
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER', default='') | default(omit) }}"
